# Generated by Django 4.0.4 on 2022-05-17 16:35

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genders_interested_in',
            field=models.ManyToManyField(related_name='profiles_interested', to='api.gender'),
        ),
        migrations.AddField(
            model_name='profile',
            name='long_description',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='api.gender'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=api.models.user_directory_path)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='api.location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='locations_interested_in',
            field=models.ManyToManyField(related_name='profiles_interested', to='api.location'),
        ),
    ]
