# Generated by Django 4.0.4 on 2022-05-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_skip_pair_message_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_types_interested_in',
            field=models.ManyToManyField(related_name='profiles', to='api.relationshiptype'),
        ),
    ]
