# Generated by Django 4.0.4 on 2022-05-24 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_relationshiptype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='genders_interested_in',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='locations_interested_in',
        ),
        migrations.AddField(
            model_name='profile',
            name='genders_attracted_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles_interested', to='api.gender'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='api.gender'),
        ),
    ]
